namespace: "ipchama"
name: "inline_python"
version: "1.0.0"
readme: "README.md"
authors:
    - "ipchama (https://github.com/ipchama/inline-python)"
dependencies: []
license:
    - "Apache 2.0"
tags:
    - python
    - jinja2
    - templates
    - inline
    - filter
repository: "https://github.com/ipchama/inline-python"